### ISSUE TITLE
Nuxt Bridge Stable

### ISSUE THREAD

**Issue by wattanx** [nuxt/bridge#1011]
```[tasklist]
### Tasks
- [x] additional test fixtures
- [x] track upstream changes
- [ ] https://github.com/nuxt/bridge/issues/1000
```
