### ISSUE TITLE
Prepare Nuxt 4

### ISSUE THREAD

**Issue by wattanx** [nuxt/bridge#1263]
We would like to make it as compatible with the changes in Nuxt 4 as possible, to facilitate a smoother migration.

```[tasklist]
### Tasks
- [ ] Default `data` and `error` values in `useAsyncData` and `useFetch`
- [ ] Removal of deprecated `boolean` values for `dedupe` option when calling `refresh` in `useAsyncData` and `useFetch`
- [ ] Shallow Data Reactivity in `useAsyncData` and `useFetch`
```
