### ISSUE TITLE
Nuxt Bridge RC

### ISSUE THREAD

**Issue by Atinux** [nuxt/bridge#891]
```[tasklist]
### Tasks
- [ ] additional test fixtures
- [ ] https://github.com/nuxt/bridge/issues/49
- [ ] https://github.com/nuxt/nuxt/pull/22815
- [ ] https://github.com/nuxt/bridge/pull/819
```

**Comment by chz** [comment]
Any news? @danielroe , @Atinux All we need this RC

**Comment by danielroe** [comment]
You can expect RC1 very shortly.
